
name: DevCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: Nhatcuong221192/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.5c6262549df6425aa2c4078afc74d8ae }}
